version: "3"

services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - 6379:6379
  arq-dashboard:
    image: ghcr.io/b3n4kh/arq-dashboard
    container_name: arq-dashboard
    ports:
      - 8000:8000
    environment:
      - ARQ_DASHBOARD_REDIS_URL=redis://redis:6379
    links:
      - redis
